# Generated by Django 2.2.5 on 2019-12-30 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='イベント名')),
                ('type', models.IntegerField(choices=[(1, '練習'), (2, '試合'), (3, '飲み会'), (4, 'その他イベント')], default=1, verbose_name='種類')),
                ('date_time', models.DateField(verbose_name='日時')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='時刻')),
                ('place', models.CharField(max_length=100, verbose_name='場所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('num_join', models.IntegerField(default=0, verbose_name='人数(参加)')),
                ('num_pend_join', models.IntegerField(default=0, verbose_name='人数(参加より保留)')),
                ('num_pend_def', models.IntegerField(default=0, verbose_name='人数(不参加より保留)')),
                ('num_cancel', models.IntegerField(default=0, verbose_name='人数(キャンセル)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, verbose_name='内容')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proto1.Event', verbose_name='イベント')),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_state', models.IntegerField(choices=[(1, '参加'), (2, '保留(参加より)'), (3, '保留(不参加より)'), (4, 'キャンセル')], default=1, verbose_name='参加状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proto1.Event', verbose_name='イベント')),
                ('user', models.ForeignKey(on_delete=models.SET('削除されたユーザ'), to=settings.AUTH_USER_MODEL, verbose_name='参加ユーザ')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
