# Generated by Django 2.2.5 on 2019-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='イベント名')),
                ('type', models.IntegerField(choices=[(1, '練習'), (2, '試合'), (3, '飲み会'), (4, '合宿'), (5, 'グリトマカップ'), (6, 'その他イベント')], default=1, verbose_name='種類')),
                ('date', models.DateTimeField(verbose_name='日時')),
                ('place', models.CharField(max_length=50, verbose_name='場所')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
